services:
  - type: web
    name: laravel-api
    runtime: php
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:ART6rI6G30DOQ9pyg4nRoeu97kJjU9KTc5RbVQ0lNEo=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-cv86g2in91rc73cgdou0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: api_crud_ristorante
      - key: DB_USERNAME
        value: api_crud_ristorante_user
      - key: DB_PASSWORD
        value: IWBjJGeadmt2oVruJgMAHuaYgZDqN65M
