services:
  - type: web
    name: laravel-app
    runtime: php
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:your_generated_key
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: your_render_db_host
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: your_render_db_name
      - key: DB_USERNAME
        value: your_render_db_user
      - key: DB_PASSWORD
        value: your_render_db_password
